name: HifiGan
train_dataset: manifests/VD/voc_VD_train.json
validation_datasets: manifests/VD/voc_VD_val.json
sample_rate: 48000
n_mel_channels: 80
n_window_size: 1024
n_window_stride: 256
n_fft: 1024
lowfreq: 0
highfreq: 8000
window: hann
train_n_segments: 8192
train_max_duration: null
train_min_duration: 0.75
val_n_segments: 66048
val_max_duration: null
val_min_duration: 3
defaults:
- model/generator: v1
- model/train_ds: train_ds
- model/validation_ds: val_ds
model:
  preprocessor:
    _target_: nemo.collections.asr.parts.preprocessing.features.FilterbankFeatures
    nfilt: ${n_mel_channels}
    lowfreq: ${lowfreq}
    highfreq: ${highfreq}
    n_fft: ${n_fft}
    n_window_size: ${n_window_size}
    n_window_stride: ${n_window_stride}
    pad_to: 0
    pad_value: -11.52
    sample_rate: ${sample_rate}
    window: ${window}
    normalize: null
    preemph: null
    dither: 0.0
    frame_splicing: 1
    log: true
    log_zero_guard_type: clamp
    log_zero_guard_value: 1.0e-05
    mag_power: 1.0
    use_grads: false
    exact_pad: true
  optim:
    _target_: torch.optim.AdamW
    lr: 1.0e-05
    betas:
    - 0.8
    - 0.99
  max_steps: 2500000
  l1_loss_factor: 45
  denoise_strength: 0.0025
  max_epochs: 1000
  train_ds:
    dataset:
      _target_: nemo.collections.tts.torch.data.VocoderDataset
      manifest_filepath: manifests/VD/voc_VD_train.json
      min_duration: 0
      n_segments: 8192
      max_duration: 100
      sample_rate: 48000
    dataloader_params:
      drop_last: false
      shuffle: true
      batch_size: 32
      num_workers: 4
  validation_ds:
    dataset:
      _target_: nemo.collections.tts.torch.data.VocoderDataset
      manifest_filepath: manifests/VD/voc_VD_val.json
      min_duration: 0
      n_segments: 66150
      max_duration: 100
      sample_rate: 48000
    dataloader_params:
      drop_last: false
      shuffle: false
      batch_size: 32
      num_workers: 4
  generator:
    _target_: nemo.collections.tts.modules.hifigan_modules.Generator
    resblock: 1
    upsample_rates:
    - 8
    - 8
    - 2
    - 2
    upsample_kernel_sizes:
    - 16
    - 16
    - 4
    - 4
    upsample_initial_channel: 512
    resblock_kernel_sizes:
    - 3
    - 7
    - 11
    resblock_dilation_sizes:
    - - 1
      - 3
      - 5
    - - 1
      - 3
      - 5
    - - 1
      - 3
      - 5
trainer:
  num_nodes: 1
  devices: 1
  accelerator: gpu
  precision: 32
  max_steps: ${model.max_steps}
  accumulate_grad_batches: 1
  enable_checkpointing: false
  logger: false
  log_every_n_steps: 100
  check_val_every_n_epoch: 10
  benchmark: false
  max_epochs: 1000
exp_manager:
  exp_dir: models/finetuned
  name: ${name}
  create_tensorboard_logger: true
  create_checkpoint_callback: true
  checkpoint_callback_params:
    monitor: val_loss
    mode: min
  create_wandb_logger: false
  wandb_logger_kwargs:
    name: null
    project: null
    entity: null
  resume_if_exists: false
  resume_ignore_no_checkpoint: false
init_from_pretrained_model: tts_hifigan
phoneme_dict_path: tts_dataset_files/cmudict-0.7b_nv22.10
heteronyms_path: tts_dataset_files/heteronyms-052722
whitelist_path: tts_dataset_files/lj_speech.tsv
